services:
  sipiru:
    build: .
    container_name: sipiru
    restart: always 
    env_file:
      - .env   # <--- load environment untuk container
    environment:
      PYTHONUNBUFFERED: 1 
    volumes:
      - .:/app
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true